server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tMun58VHwvJoBg487w2
    keySecret: ViRzpQvn76QgS0Y42aSs2sxUpSSFxq
    bucketName: srb-file-200921-eagle